-- DIACONOS
INSERT INTO eleicao.candidato VALUES(0,'Nulo',2);
INSERT INTO eleicao.candidato VALUES(1,'CARMELINDO JESUS CARDOSO RODRIGUES',2);
INSERT INTO eleicao.candidato VALUES(2,'DANIEL DA SILVA QUADROS',2);
INSERT INTO eleicao.candidato VALUES(3,'DEIVID COSTA NASCIMENTO',2);
INSERT INTO eleicao.candidato VALUES(4,'EDERSON DA CONCEIÇÃO KEPPELER',2);
INSERT INTO eleicao.candidato VALUES(5,'JOSE REINALDO MENGER BOBSIN',2);
INSERT INTO eleicao.candidato VALUES(6,'LUIS CARLOS DA SILVA VIEGAS JUNIOR',2);
INSERT INTO eleicao.candidato VALUES(7,'SAMUEL ZANETTI BARRETO',2);
INSERT INTO eleicao.candidato VALUES(8,'TIAGO MEDEIROS RODRIGUES DA SILVA',2);

