--DIACONISA
INSERT INTO ipr_vota2010.candidato VALUES(0,'Nulo',3);
INSERT INTO ipr_vota2010.candidato VALUES(1,'AUGUSTA SOUZA FRANCISCO BOBSIN',3);
INSERT INTO ipr_vota2010.candidato VALUES(2,'ANA NAIRA TARRAGO DOS SANTOS',3);
INSERT INTO ipr_vota2010.candidato VALUES(3,'ELIETE BOBSIN DA SILVA LIMA',3);
INSERT INTO ipr_vota2010.candidato VALUES(4,'JANETE DSE SOUZA BOBSIN',3);
INSERT INTO ipr_vota2010.candidato VALUES(5,'KARISE CARDOSO PIUCO',3);
INSERT INTO ipr_vota2010.candidato VALUES(6,'MARGARETE DA SILVA BOBSIN',3);
INSERT INTO ipr_vota2010.candidato VALUES(7,'MARLI MARIA TARRAGO SANTOS',3);
INSERT INTO ipr_vota2010.candidato VALUES(8,'JOSIELE BOBSIN RODRIGUES',3);
INSERT INTO ipr_vota2010.candidato VALUES(9,'OTILIA COSTA DA LUZ',3);
INSERT INTO ipr_vota2010.candidato VALUES(11,'MARISTELA TEDESCHI GOMES',3);


